### ISSUE TITLE
mesoscale - det: Address Bugzilla 1606 - counting of models in python scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#627]
On 20241228, evs_mesoscale_sref_cape_past90days_plots failed with the following error.

Traceback (most recent call last):

>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1622, in <module>
>     main()
>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1475, in main
>     plot_lead_average(
>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 707, in plot_lead_average
>     if math.isinf(y_mod_min):
> UnboundLocalError: local variable 'y_mod_min' referenced before assignment

Please double check all scripts and fix if needed in the next upgrade:

- [x] ./ush/mesoscale/time_series.py
- [x] ./ush/mesoscale/lead_average.py
- [x] ./ush/mesoscale/valid_hour_average.py
- [x] ./ush/mesoscale/threshold_average.py

See #624 for what was delivered to fix the failed job.

**Comment by PerryShafran-NOAA** [comment]
All 4 files in mesoscale det are already correct.

**Comment by malloryprow** [comment]
Wonderful news!
