### ISSUE TITLE
mesoscale - ens: Address Bugzilla 1606 - counting of models in python scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#628]
On 20241228, evs_mesoscale_sref_cape_past90days_plots failed with the following error.

Traceback (most recent call last):

>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1622, in <module>
>     main()
>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1475, in main
>     plot_lead_average(
>   File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 707, in plot_lead_average
>     if math.isinf(y_mod_min):
> UnboundLocalError: local variable 'y_mod_min' referenced before assignment

Please double check all scripts and fix if needed in the next upgrade:

- [ ] ./ush/mesoscale/ush_sref_plot_cnv_py/valid_hour_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_cnv_py/threshold_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_cnv_py/time_series.py
- [ ] ./ush/mesoscale/ush_sref_plot_cnv_py/lead_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_py/valid_hour_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_py/threshold_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_py/time_series.py
- [ ] ./ush/mesoscale/ush_sref_plot_py/lead_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_precip_py/valid_hour_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_precip_py/threshold_average.py
- [ ] ./ush/mesoscale/ush_sref_plot_precip_py/time_series.py
- [ ] ./ush/mesoscale/ush_sref_plot_precip_py/lead_average.py

See #624 for what was delivered to fix the failed job.

**Comment by AliciaBentley-NOAA** [comment]
This was addressed in multiple PRs, but most recently in PR #892!
