### ISSUE TITLE
cam - det: Address Bugzilla 1606 - counting of models in python scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#630]
On 20241228, evs_mesoscale_sref_cape_past90days_plots failed with the following error.

Traceback (most recent call last):

File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1622, in
main()
File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1475, in main
plot_lead_average(
File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 707, in plot_lead_average
if math.isinf(y_mod_min):
UnboundLocalError: local variable 'y_mod_min' referenced before assignment

Please double check all scripts and fix if needed in the next upgrade:

- [x] ./ush/cam/valid_hour_average.py
- [x] ./ush/cam/threshold_average.py
- [x] ./ush/cam/time_series.py
- [x] ./ush/cam/lead_average.py

See https://github.com/NOAA-EMC/EVS/pull/624 for what was delivered to fix the failed job.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow It looks like the cam scripts already have the needed fix:
- [ush/cam/valid_hour_average.py](https://github.com/NOAA-EMC/EVS/blob/22889222b796e582a4e2bcf9f961ab9363c112fa/ush/cam/valid_hour_average.py#L765C13-L768C26)
- [ush/cam/threshold_average.py](https://github.com/NOAA-EMC/EVS/blob/22889222b796e582a4e2bcf9f961ab9363c112fa/ush/cam/threshold_average.py#L562C13-L565C26)
- [ush/cam/time_series.py](https://github.com/NOAA-EMC/EVS/blob/22889222b796e582a4e2bcf9f961ab9363c112fa/ush/cam/time_series.py#L712C13-L716C26)
- [ush/cam/lead_average.py](https://github.com/NOAA-EMC/EVS/blob/22889222b796e582a4e2bcf9f961ab9363c112fa/ush/cam/lead_average.py#L761C13-L764C26)

👍 I think the cam jobs are safe from the bug in #624.

**Comment by malloryprow** [comment]
Great news! I will close it!
