### ISSUE TITLE
analyses: Address Bugzilla 1606 - counting of models in python scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#635]
On 20241228, evs_mesoscale_sref_cape_past90days_plots failed with the following error.

Traceback (most recent call last):

File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1622, in
main()
File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1475, in main
plot_lead_average(
File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 707, in plot_lead_average
if math.isinf(y_mod_min):
UnboundLocalError: local variable 'y_mod_min' referenced before assignment

Please double check all scripts and fix if needed in the next upgrade:

- [x] ./ush/analyses/valid_hour_average.py
- [x] ./ush/analyses/threshold_average.py
- [x] ./ush/analyses/time_series.py
- [x] ./ush/analyses/lead_average.py

See https://github.com/NOAA-EMC/EVS/pull/624 for what was delivered to fix the failed job.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I have confirmed that all these scripts are correctly set in the analysis ush plot codes.

**Comment by malloryprow** [comment]
Thanks!
