### ISSUE TITLE
global_ens: Address Bugzilla 1606 - counting of models in python scripts

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EVS#636]
On 20241228, evs_mesoscale_sref_cape_past90days_plots failed with the following error.

Traceback (most recent call last):

File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1622, in
main()
File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 1475, in main
plot_lead_average(
File "/lfs/h1/ops/prod/packages/evs.v1.0.15/ush/mesoscale/ush_sref_plot_py/lead_average.py", line 707, in plot_lead_average
if math.isinf(y_mod_min):
UnboundLocalError: local variable 'y_mod_min' referenced before assignment

Please double check all scripts and fix if needed in the next upgrade:

- [x] ./ush/global_ens/time_series.py
- [x] ./ush/global_ens/lead_average.py
- [ ] ./ush/global_ens/ush_gens_plot_py/time_series.py
- [ ] ./ush/global_ens/ush_gens_plot_py/lead_average.py

See https://github.com/NOAA-EMC/EVS/pull/624 for what was delivered to fix the failed job.

**Comment by GwenChen-NOAA** [comment]
@SamiraArdani-NOAA, does PR #755 fix this bug in the following scripts?

ush/global_ens/time_series.py
ush/global_ens/lead_average.py

**Comment by SamiraArdani-NOAA** [comment]
> [@SamiraArdani-NOAA](https://github.com/SamiraArdani-NOAA), does PR [#755](https://github.com/NOAA-EMC/EVS/pull/755) fix this bug in the following scripts?
> 
> ush/global_ens/time_series.py ush/global_ens/lead_average.py

@GwenChen-NOAA, yes, it fixes for Bugzilla 1606 but I only addressed it in the checked marked /ush scripts (wave-related scripts).

**Comment by SamiraArdani-NOAA** [comment]
> [@SamiraArdani-NOAA](https://github.com/SamiraArdani-NOAA), does PR [#755](https://github.com/NOAA-EMC/EVS/pull/755) fix this bug in the following scripts?
> 
> ush/global_ens/time_series.py ush/global_ens/lead_average.py

@GwenChen-NOAA, yes, it fixes for Bugzilla 1606.

**Comment by GwenChen-NOAA** [comment]
> > [@SamiraArdani-NOAA](https://github.com/SamiraArdani-NOAA), does PR [#755](https://github.com/NOAA-EMC/EVS/pull/755) fix this bug in the following scripts?
> > ush/global_ens/time_series.py ush/global_ens/lead_average.py
> 
> [@GwenChen-NOAA](https://github.com/GwenChen-NOAA), yes, it fixes for Bugzilla 1606 but I only addressed it in the checked marked /ush scripts (wave-related scripts).

Great!  I will take care the plotting scripts for the atmos component.  Thanks!

**Comment by GwenChen-NOAA** [comment]
This issue is resolved by PRs #755 and #781.
